// flow-typed signature: 835c115abbc7c658be67da437d18ce7c
// flow-typed version: <<STUB>>/bulma_v^0.4.3/flow_v0.51.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bulma'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bulma' {
  declare module.exports: any;
}
