// flow-typed signature: 175e2c95aeb73d7ddab6e10157205451
// flow-typed version: <<STUB>>/bulma_v^0.4.1/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bulma'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bulma' {
  declare module.exports: any;
}
