// flow-typed signature: b4465ac518ce7f8246df767a5989e27e
// flow-typed version: <<STUB>>/bulma_v^0.4.0/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bulma'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'bulma' {
  declare module.exports: any;
}
